name: Java CI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile and Run Tests
      run: |
        # Navigate to the src directory (handle spaces in folder names)
        cd "Assignment 2/src"
        
        # Create a directory for compiled classes
        mkdir -p build/classes

        # Compile the Java files, including libraries and source directories
        javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:main/java:test/java" \
              -d build/classes \
              main/java/LoginApp.java test/java/LoginAppTest.java

        # Run the tests using JUnit
        java -cp "build/classes:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" \
             org.junit.runner.JUnitCore LoginAppTest
